### PR TITLE
Remove inital wait/sleep in github actions.

### LINKED ISSUE #174: Find way to remove sleeps from CI pipeline
It adds a lot of time to the time it takes to run tests, and I think it should be possible to use some tricks to check whether we can continue instead of using sleeps. Not sure how yet...

### PR DESCRIPTION
**Pull request by morrieinmaas**
Replace it by checking the logs of one of the aca-py containers for signalling ready.

Best I could come up with for now. That's what works for me on local machine. 

Happy if there are better suggestions. Couldn't find any poll events to look for in particular as suggested in the ticket.

closes #174

### CODE REVIEW

**Comment by morrieinmaas** [comment]
also I left the sleep in for the retry on purpose in a better-safe-than-sorry kinda way. Can also change that if desired.

**Comment by morrieinmaas** [comment]
Runs through now. Saves roughly 3-6 minutes compared to previous implementation when looking at the entire runtime of the ci/cd pipeline runs under the actions tab

**Review by TimoGlastra — APPROVED** [review]
That looks complex 😬

**Comment by morrieinmaas** [comment]
It;s really just the only thing i could think of right away. Not that complex really. Just checks the logs of aca-py container for this "ascii art" bit aca-py logs when ready to go:

```bash
::::::::::::::::::::::::::::::::::::::::::::::
:: Alice                                    ::
::                                          ::
::                                          ::
:: Inbound Transports:                      ::
::                                          ::
::   - http://0.0.0.0:3020                  ::
::                                          ::
:: Outbound Transports:                     ::
::                                          ::
::   - http                                 ::
::   - https                                ::
::                                          ::
:: Public DID Information:                  ::
::                                          ::
::   - DID ....
```

when that happens it's ready to go. That's pretty much it.

**Pull request merged**
