### PR TITLE
:memo: Update README

### PR DESCRIPTION
**Pull request by ff137**
- Fixes Codacy badge links
- Updates "under development" note
- Add more badges

### CODE REVIEW

**Comment by ff137** [comment]
@rblaine95 What do you think about adding badges that show Mise / Tilt compatibility?

e.g. one of:

Mise:
Mise
Mise
Mise

Tilt:
Tilt
Tilt
Tilt

**Comment by ff137** [comment]
Here's the current new badges I'm thinking to add:
image

Some other options, thanks to GPT: 
build status, last release date, supported platforms, dependency management tool, "actively maintained" status
(most of those are already visible on the page)

@wdbasson @cl0ete Let me know what you think!

**Comment by ff137** [comment]
Also, considering that acapy is no longer "aries cloud agent", thought we can rename the project to `didx-cloud`. Just in the readme title for now, and repo rename next year

**Review by rblaine95 — APPROVED** [review]

**Review by cl0ete — APPROVED** [review]
:rocket:

**Review by rblaine95 — APPROVED** [review]

**Pull request merged**
