### PR TITLE
feat: issuer onboarding with multiuse invite on trust registry

### LINKED ISSUE #252: Create multi-use invite on issuer creation and invite added to trust registry
@morrieinmaas can you please pick this up. Should be a fairly small change

### PR DESCRIPTION
**Pull request by morrieinmaas**
closes #252 

Signed-off-by: Moriarty <moritz@animo.id>

### CODE REVIEW

**Comment by morrieinmaas** [comment]
@TimoGlastra Do you have any feedback for this?

**Review by TimoGlastra — COMMENTED** [review]
Code looks good. Could you add some tests for this flow?

**Comment by morrieinmaas** [comment]
> Code looks good. Could you add some tests for this flow?

Sure. Do you have anything more specific in mind. I added some tests to check whether this is actually written to the trust registry

**Comment by TimoGlastra** [comment]
Ah totally missed those test files 😊

**Review by TimoGlastra — APPROVED** [review]

**Comment by morrieinmaas** [comment]
> Ah totally missed those test files 😊

ahhhh ok, cool.

**Pull request merged**
