### PR TITLE
feat: add transaction endorser service

### PR DESCRIPTION
**Pull request by TimoGlastra**
Dependant on #231, which needs to be merged first.

Adds a transaction endorser service that listens for endorsement requests and accepts them if they conform to the trust registry rules.

### CODE REVIEW

**Comment by morrieinmaas** [comment]
@TimoGlastra this has merge conflicts still

**Comment by TimoGlastra** [comment]
Ugh.. not sure why tests are failing in CI :(

**Comment by morrieinmaas** [comment]
@TimoGlastra got this working. Any more feedback?

**Comment by TimoGlastra** [comment]
Live check seems like a good solution to me!

**Comment by TimoGlastra** [comment]
> @TimoGlastra got this working. Any more feedback?

Nope, really great work on fixing this!! Thanks

**Comment by TimoGlastra** [comment]
Can I merge or do you first want to merge some other PRs @morrieinmaas?

**Comment by morrieinmaas** [comment]
@TimoGlastra curling the aca-py for status works locally but breaks in gh actions. Tried swallowing the error(s) like so

```bash
i=0
echo waiting for aca-py container to startup
./manage up-daemon-usecache
while [ $i -le 300 ]
do
  STATE1=$(curl -k -X 'GET' 'http://0.0.0.0:3021/status/ready'  -H 'accept: application/json' 2>/dev/null)
  STATE2=$(curl -k -X 'GET' 'http://0.0.0.0:4021/status/ready'  -H 'accept: application/json' 2>/dev/null)
  sleep 1
  ((i++))
  echo Waiting for Aca-py containers to be ready ${i}/300
  if [[ -z "${STATE1}" && -z "${STATE2}" ]]; then
    echo Containers snot reachable yet
  else
    STATUS1=$(echo $STATE1 | jq .ready)
    STATUS2=$(echo $STATE2 | jq .ready)
    echo
    echo Agent 1 is ready: ${STATUS1}
    echo Agent 2 is ready: ${STATUS2}
    echo 
    if [[ $STATUS1 == 'true' && $STATUS2 == 'true'  ]]; echo wait over; then exit 0; fi  
  fi
done
```

and some other ways. In GH Actions there always seems to be a way this breaks nontheless. So I'd say let's keep it as it is for now as it works.

**Comment by TimoGlastra** [comment]
Yeah sure! Feel free to merge when you're ready

**Pull request merged**
